# Generated by Django 5.2.1 on 2025-05-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
    ]
